"""Create new schema

Revision ID: cc4b5fcc7c23
Revises: 
Create Date: 2024-07-11 10:52:35.214011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc4b5fcc7c23'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('country_of_origin', sa.String(length=150), nullable=False),
    sa.Column('question_a', sa.Integer(), nullable=False),
    sa.Column('signal_line', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('access_time',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('access_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('time1', sa.Float(), nullable=False),
    sa.Column('time2', sa.Float(), nullable=False),
    sa.Column('paw1', sa.Float(), nullable=False),
    sa.Column('paw2', sa.Float(), nullable=False),
    sa.Column('pes1', sa.Float(), nullable=False),
    sa.Column('pes2', sa.Float(), nullable=False),
    sa.Column('register_time', sa.DateTime(), nullable=False),
    sa.Column('signal_line', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('result')
    op.drop_table('access_time')
    op.drop_table('user')
    # ### end Alembic commands ###
